### ISSUE TITLE
Iframe usage

### ISSUE THREAD

**Issue by richie-south** [atlassian/pragmatic-drag-and-drop#103]
Hello. I'm trying to drag draggable's that start inside an iframe and ends in the same iframe but no actions are firing. 
Not trying to drag items into or out side of the iframe. All my components are inside my iframe and i'm trying to move them around.  Looks like their are not listener for iframes only the parent window?

i've looked at `dropTargetForExternal` with `monitorForExternal` but they seems to be more focused on moving items into our out of an iframe. And no examples for iframes are available what i can see?

Looks like a few other people have wanted to do what i'm trying but with no success: https://github.com/atlassian/pragmatic-drag-and-drop/issues/48 and https://github.com/atlassian/pragmatic-drag-and-drop/issues/24

This might not be possible with  pragmatic drag and drop? :)

**Comment by alexreardon** [comment]
> I'm trying to drag draggable's that start inside an iframe and ends in the same iframe but no actions are firing.

This is supported. Just set up your draggables and drop targets in your iframe document as you would outside of an iframe.

If you would like further assistance for this, please provide a standalone example for us to debug. Cheers

**Comment by alexreardon** [comment]
See https://github.com/atlassian/pragmatic-drag-and-drop/issues/24#issuecomment-2290171561
