### ISSUE TITLE
Android + Chrome@128 not working?

### ISSUE THREAD

**Issue by ghost** [atlassian/pragmatic-drag-and-drop#112]
We use Pragmatic Drag and Drop for tree-style D&D throughout our product and have received a number of reports of drag and drop failing to 'start' a drag across multiple Android phones. It seems to change the state of the target item as if a drag had started, but doesn't create the floating item or properly show the indicator state.

We've been able to reproduce the report on a test device (against both our site and the examples site), and are not currently aware of a mitigation/fix. The issue seems to also occur with many (if not all of) the official examples available at https://atlassian.design/components/pragmatic-drag-and-drop/examples so we do not believe the issue is specific to our implementation.

The issue seems to have started a few days to a week ago, without any dependency or implementation changes on our end. Everything seems to work on a device with Chrome version 127.0.6533, so we believe it may be caused by a change in Chrome/Chromium version 128.

We're aware of the issue occurring with Chrome and Brave on these device configurations (and expect other chromium-based android browsers to be affected as well):

- Pixel 8 (Android 14, Brave 1.69.153 with Chromium 128.0.6613.85)
- Nokia 5.4 (Android 12, Chrome 128.0.6613.99)
- Samsung Galaxy A12 (Android 12, Brave 1.69.60 with Chromium 128.0.6613.114)

This screencap shows the issue on our site (loosely based on the tree example):
https://github.com/user-attachments/assets/c0c06f32-74cf-4f77-ab1d-ae8e668d9dab

This screncap shows the issue on the examples site:
https://github.com/user-attachments/assets/7b7c8e33-8c79-4807-b545-22a116aa4c50

We also received this video from an affected end-user. The first portion is Brave (Chromium v128), the second browser is Kiwi, which works as expected and uses Chromium v124.
https://imgur.com/bDMEOTe

**Comment by alexreardon** [comment]
I am currently unable to verify this issue as I don't have access to Chrome@128 on Android (@127 is the latest available to me). 

If you have access to Chrome@128, can you please validate whether this minium case works?

- Standalone: https://4q5x6d.csb.app/
- Source code: https://codesandbox.io/p/sandbox/drag-and-drop-for-andriod-4q5x6d

**Comment by alexreardon** [comment]
I've downloaded Chrome@beta on Android, which is running Chrome@129 - and I am having no issues with the [standalone platform drag and drop example](https://4q5x6d.csb.app/) or with our [pdnd board example](https://atlassian.design/components/pragmatic-drag-and-drop/examples) 🤔

**Comment by alexreardon** [comment]
Thanks so much for looking into this. Sounds like it's time to raise a bug with Chrome. 

- @inventorgg can you please [raise a bug with chrome](https://issues.chromium.org/issues/wizard)? You have all the data so I think it would be best if you raise the bug. I personally have not been able to reproduce the issue yet.
- In your bug report, I think it would be clearest to lead with the standalone demo
- Can you please link the bug report here? I'll give input on the Chrome bug as needed

Cheers

**Comment by ebtsi** [comment]
Thanks for your help! Just created the issue at https://issues.chromium.org/u/0/issues/363930156

**Comment by alexreardon** [comment]
Thank you 🫡

**Comment by ColonelThirtyTwo** [comment]
I'm not able to interact with any of the examples on https://atlassian.design/components/pragmatic-drag-and-drop/examples/ using touch. Touches just scroll the page. I've tested it on Firefox and Chrome on Android, as well as Firefox's and Chromium's touch emulation on Linux.

Here's a video I took on Firefox for Android. I was attempting to drag the handles, and you can occasionally see one of them briefly highlight from hovering, but the screen scrolls instead of moving the items.

https://github.com/user-attachments/assets/28d90863-44c7-4dc0-b2fa-83f198ea28b4

**Comment by goodjobjohn** [comment]
+1
Chrome 128.0.6613.127
firefox nightly 132.0a1 (Build #2016043439)
android 12

**Comment by gibtree** [comment]
I'm not sure if this helps, but I can also reproduce this failure on Desktop on both Firefox and Chrome by using their Mobile emulation devtools. The touch events don't seem to be picked up at all by the examples page on a browser.

[Screencast from 09-13-2024 09:46:45 PM.webm](https://github.com/user-attachments/assets/7fdfbdc1-13c8-497b-8525-2a3f4d935cd8)
