### ISSUE TITLE
Docs: Links to optional packages not working

### ISSUE THREAD

**Issue by mattbal** [atlassian/pragmatic-drag-and-drop#120]
All the [links](https://atlassian.design/components/pragmatic-drag-and-drop/optional-packages/) to optional packages are broken. They just redirect to https://atlassian.design/components/pragmatic-drag-and-drop/about

**Comment by mattbal** [comment]
Using the sidebar nav menu let's you visit the optional package pages. Looks like the links just need to be updated

**Comment by alexreardon** [comment]
I'll update these asap

**Comment by michaelabrahamian** [comment]
These have been fixed ✅
