### ISSUE TITLE
CSS transform on dragged element is not preserved by the dragged item

### ISSUE THREAD

**Issue by ericbiewener** [atlassian/pragmatic-drag-and-drop#129]
<img width="166" alt="Screenshot 2024-09-24 at 6 27 25 AM" src="https://github.com/user-attachments/assets/feac5395-6790-4598-80fa-d7135776544d">

This appears to be a limitation of the HTML5 drag & drop API ([Codepen](https://codepen.io/ericbiewener/pen/RwXwdXb) indicating this), so feel free to close this issue if pragmatic doesn't offer a solution. Posting this in part just to have it discoverable by future devs.

One potential solution is of course to make a wrapping container draggable, rather than the transformed element itself. But this produces other visual issues, such as the clipping are on the dragged item including an opaque gray background, and potentially even some content outside the DOM of the dragged element (note the few pixels of purple on the left):

<img width="204" alt="Screenshot 2024-09-24 at 6 42 40 AM" src="https://github.com/user-attachments/assets/386da503-c6d7-49d6-8c95-446a888c723e">

**Comment by tarun111111** [comment]
Than use the shadow border usess to fix them

**Comment by alexreardon** [comment]
- unfortunately, there are some [known bugs](https://atlassian.design/components/pragmatic-drag-and-drop/web-platform-design-constraints#native-drag-previews) with native drag previews (elements with transforms being one of them). The issue with transforms seems to impact Safari the most, so one option is to use the transform on Chrome, and disable the transform in `onGenerateDragPreview` for Safari
- [setCustomNativeDragPreview](https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/drag-previews#approach-1-use-a-custom-native-drag-preview) helps smooth over most issues if you haven't tried that

**Comment by michaelabrahamian** [comment]
Closing this, but feel free to re-raise if you have further questions 😄
