### ISSUE TITLE
drop doesn't work with alt/meta keys

### ISSUE THREAD

**Issue by martinhonza** [atlassian/pragmatic-drag-and-drop#137]
Hey,
I encountered an issue that if I try to drag and drop while I press alt/meta key modifier the dragged item just returns back to original position and onDrop is not called.  If I use `monitorForElements` then it is called, but `location.current.dropTarget` is empty. It seems to work with ctrl/shift.

It can be visible on any example with logs in onDrop, eg https://codesandbox.io/p/sandbox/pmdxgv

**Comment by alexreardon** [comment]
We are at the mercy of the web platform for this one. Right now, in Chrome, holding the `meta` key during a drag cancels the drag

**Comment by alexreardon** [comment]
We could raise an issue with Chrome about this one though as I don't think they are following the spec
