### ISSUE TITLE
How to change the cursor when dragging?

### ISSUE THREAD

**Issue by joetidee** [atlassian/pragmatic-drag-and-drop#144]
Not sure how to do this. I am using styled components for styling the draggables (f that makes a difference), but as the preview is an image, I'm not sure how to do this?

**Comment by michaelabrahamian** [comment]
Hey @joetidee, thanks for reaching out! Cursors are a tough problem due to platform constraints and inconsistencies. 

We have some guidance about cursors here: https://atlassian.design/components/pragmatic-drag-and-drop/web-platform-design-constraints/#cursors
