### ISSUE TITLE
Links in the documentation seem to be broken

### ISSUE THREAD

**Issue by joetidee** [atlassian/pragmatic-drag-and-drop#145]
For example, this page - https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about - all of the links to the optional element utilities are directing to the main home page.

**Comment by psychedelicious** [comment]
All the content is still there, but you have to use the navigation sidebars to get to it.

**Comment by joetidee** [comment]
That really isn't obvious.

**Comment by michaelabrahamian** [comment]
Thanks for raising this. We've had issues with links after a recent internal change to our documentation platform. 

We'll spend some time to go through and update them.

**Comment by michaelabrahamian** [comment]
We've gone through all the pragmatic docs pages and all broken links should now be fixed. Please let us know if you find any more though!
