### ISSUE TITLE
Phantom release of `@atlaskit/pragmatic-drag-and-drop-auto-scroll` 2.0

### ISSUE THREAD

**Issue by sambauers** [atlassian/pragmatic-drag-and-drop#157]
There appears to have been a 2.0 release of the package `@atlaskit/pragmatic-drag-and-drop-auto-scroll`, but this package's code doesn't seem to be version 2.0 in this repository.

The NPM website does list a version 2.0.

The contents of the 2.0 package on NPM are viewable here: https://www.npmjs.com/package/@atlaskit/pragmatic-drag-and-drop-auto-scroll?activeTab=code

Is the 2.0 release legitimate or is this possibly a bug in CI/CD?

**Comment by alexreardon** [comment]
I'll look into it

**Comment by alexreardon** [comment]
Our repo sync runs every 24 hours and it looks like it has not run yet for today. I'll manually run the sync job now

**Comment by alexreardon** [comment]
Repo is now synced. Going forward you can expect a lag of up to 24 hours between `npm` and what is in this repo

**Comment by alexreardon** [comment]
I'll update our `README.md` to call out how frequently we update this repo to hopefully help avoid some confusion for other people too

**Comment by alexreardon** [comment]
Now added to the README.md (to be synced soon 😉)

> ## `npm` release and repo sync timing
>
> This mirror repository is currently being synced with our internal repository once a day. We publish packages to `npm` immediately as we merge new versions into the internal repository. This means that code can be released onto `npm` up to 24 hours _before_ it is available in this mirror repository.
