### ISSUE TITLE
Implement render your own drag preview

### ISSUE THREAD

**Issue by hungify** [atlassian/pragmatic-drag-and-drop#162]
I'm trying to follow this guide [non-native-custom-drag-previews.](https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/drag-previews#non-native-custom-drag-previews)

However, I have an issue regarding how to reuse or create my own with the same behavior of preserveOffsetOnSource.

```
  useEffect(() => {
    const updatePosition = () => {
      if (!previewRef.current || !input || !rect) return;

      const viewportWidth = window.innerWidth;
      const viewportHeight = window.innerHeight;

      const translateX = input.clientX - rect.width / 2;
      const translateY = input.clientY + window.scrollY - rect.height;

      previewRef.current.style.transform = `translate(${translateX}px, ${translateY}px)`;

      requestAnimationFrame(updatePosition); 
    };

    const animationFrameId = requestAnimationFrame(updatePosition);

    return () => {
      cancelAnimationFrame(animationFrameId);
    };
  }, [input, rect, viewportScroll, viewportScroll.y]);
```

[Sandbox](https://stackblitz.com/~/github.com/hungify/pragmatic-drag-and-drop-auto-scroll)

Would you happen to have any suggestions? I would greatly appreciate them.

**Comment by hungify** [comment]
I researched and completed this technique, and it produced the best results across various browsers and devices.
You can check it out in my [repo](https://github.com/hungify/pragmatic-custom-preview) and [example](https://pragmatic-custom-preview.netlify.app/).

**Comment by amazinGoing** [comment]
thank you, it helps me a lot.
