### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jeffdaley** [atlassian/pragmatic-drag-and-drop#17]
Hello,

Thanks, hugs, love ya, etc. "What a library" - me.

I'm running into broken links pretty frequently in the documentation. Some examples:

- "Reconciliation" link at https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about#draggable
- "drop target" link at https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about#drop-target-for-elements
- "`once` utility function" link at https://atlassian.design/components/pragmatic-drag-and-drop/core-package/drop-targets/#handling-ondrop-for-nested-drop-targets

Usually I'm able to find the new location based on the broken `href` but it's sort of annoying. Thanks for considering a fix!

**Comment by alexreardon** [comment]
I've made these changes. They should be released in the next few hours.

Thanks @jeffdaley!!
