### ISSUE TITLE
Change cursor while dragging

### ISSUE THREAD

**Issue by nicolo-one** [atlassian/pragmatic-drag-and-drop#19]
Hello! Is there a possibility to change the cursor during drag? Currently, when the drag action starts, the drag cursor is displayed. I'm developing an application to resize graphical elements and I want to use the 'nw-resize' cursor during resize, but I can't find a solution.
Here is an example:
![Recording-2024-04-03-120017](https://github.com/atlassian/pragmatic-drag-and-drop/assets/162106967/1ebded96-a633-4360-bbe2-3c83c6babed2)

**Comment by alexreardon** [comment]
Unfortunately this a current constraint of the web platform: https://atlassian.design/components/pragmatic-drag-and-drop/web-platform-design-constraints

I hope to raise a proposal to change this soon!
