### ISSUE TITLE
Synchronise repo with commit messages (eg. --fast-forward)

### ISSUE THREAD

**Issue by sergioisidoro** [atlassian/pragmatic-drag-and-drop#20]
At the moment all commit messages are "Synchronise latest changes".

I'm super curious to try out this lib, but since it's also in an early stage, seeing what's changing / fixed is important. Seeing only opaque commit messages is a bit scary, as we don't know what's happening 

I think Seeing the commit changes would be super helpful :)
Would it be possible to have the bot make fast forward merges when syncing?

SUPER curious to try this out. It looks like a lot of care and engineering effort was done here!

**Comment by danielweck** [comment]
I agree, the Git commit history matters to outsiders when assessing the project's qualities.
The Atlassian merges indeed look out of place.

Would it be possible to use "conventional commits" syntax for commit messages, as well as atomic "stash" for merge strategy in order to avoid scattered commit units in the chronological history?

**Comment by alexreardon** [comment]
Sharing commit messages over would be ideal 👌 

Why we are not doing that right now:

- we are technically not synchronising individual commits, rather, we are crushing all changes in a given time period for the pdnd related code into a single commit
- The Pragmatic drag and drop code lives in a monorepo which contains private packages. We opted for an approach (for now) that would not leak any (potentially) private information. Commit messages _could_ contain sensitive information that is not intended for public visibility. 
- A commit in the mono repo could span a number of packages (ie some public packages, and some private packages)

Is this problem solvable? Yes. But I wanted to give some context.

For now, you can see all the change information in our changelogs ([flourish example](https://atlassian.design/components/pragmatic-drag-and-drop/optional-packages/flourish/changelog))

Open to suggestions on how we could improve things, especially fairly low hanging options.

Perhaps one possibility for now is replicating our changelog information in Github releases, as Github releases allow you to see the code diff between versions

**Comment by alexreardon** [comment]
I'll close this issue for now, but I am keen to explore at least populating github releases with correct information from changesets
