### ISSUE TITLE
@atlaskit/pragmatic-drag-and-drop-react-accessibility has a peer dependency of react 16.8.0

### ISSUE THREAD

**Issue by patorjk** [atlassian/pragmatic-drag-and-drop#22]
I was checking out some of the [optional packages](https://atlassian.design/components/pragmatic-drag-and-drop/optional-packages/react-accessibility/code) that were suggested and got an error when I tried to install `@atlaskit/pragmatic-drag-and-drop-react-accessibility`, as it had React version ^16.8.0 as a peer dependency. This seems like it may be an error, though I noticed most of codesandbox examples are using React 16. Are newer versions of React supported?

Edit: It seemed to work fine in React 18. Also, I noticed the same peer dependency issue in several other packages (ex: @atlaskit/tokens).

**Comment by alexreardon** [comment]
Thanks!! I think we should update the peer deps to include react18 😊

**Comment by alexreardon** [comment]
Hours. It might even already be out 😇

**Comment by alexreardon** [comment]
✨**Good news**: I made this change two days ago
😭 **Bad news**: There appears to be an issue with our `npm` release pipeline and I can see the new version has not been released yet.

I am following this up now

**Comment by SzymonDukla** [comment]
Yep @alexreardon was just about to mention that 😇 amazing, cheers!

**Comment by Monu18765** [comment]
Seems not updated till now.

**Comment by SzymonDukla** [comment]
Yeah some packages seem to be updated, some (eg. tokens or flags) not (hopefully just yet) 😿 @alexreardon any news?

**Comment by alexreardon** [comment]
Good news: everything should be good on `npm` now ([example](https://www.npmjs.com/package/@atlaskit/pragmatic-drag-and-drop-react-drop-indicator?activeTab=code))

```json
"peerDependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0"
  },
```

Please let me know if you are still running into any issues

**Comment by SzymonDukla** [comment]
Great news @alexreardon thanks!

Btw may be not in scope of this package, but any chance to get some other @atlaskit packages up-to-date? Currently getting same react errors on:

- @atlaskit/motion
- @atlaskit/flag
- @atlaskit/primitives
- @atlaskit/tokens

And potentially some more
