### ISSUE TITLE
CSS transforms animations similar to react-beautiful-dnd

### ISSUE THREAD

**Issue by bricejar** [atlassian/pragmatic-drag-and-drop#3]
Hi,

Will it be possible to make animations for drag and drop within simple lists similar to react-beautiful-dnd, when dragging an item moves the other items around using css transforms ? 

I acknowledge that this might not be the recommended approach due to potential user experience and performance concerns. Nonetheless, I'd like to know if there are any inherent limitations that might hinder someone from replicating an experience similar to what was offered by react-beautiful-dnd.

**Comment by alexreardon** [comment]
Short answer:  You _could_ make something similar, but likely not exactly the same as `react-beautiful-dnd`, unless you are willing to write a lot of code

Longer answer:

The web platform drag and drop functionality doesn't work _too well_ with things shifting around: when you shift things around, you also shift their hitboxes. That said, you can get pretty far with not _too much_ trouble. See the trello part of this video:

![Show case of some examples](https://github.com/alexreardon/files/assets/2182637/2b533f88-bf3f-402f-93f2-74a466918ac4)

**Comment by masudhossain** [comment]
> Short answer: You _could_ make something similar, but likely not exactly the same as `react-beautiful-dnd`, unless you are willing to write a lot of code
> 
> Longer answer:
> 
> The web platform drag and drop functionality doesn't work _too well_ with things shifting around: when you shift things around, you also shift their hitboxes. That said, you can get pretty far with not _too much_ trouble. See the trello part of this video:
> 
> ![Show case of some examples](https://private-user-images.githubusercontent.com/2182637/314914116-2b533f88-bf3f-402f-93f2-74a466918ac4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNTM2MDksIm5iZiI6MTcxMjM1MzMwOSwicGF0aCI6Ii8yMTgyNjM3LzMxNDkxNDExNi0yYjUzM2Y4OC1iZjNmLTQwMmYtOTNmMi03NGE0NjY5MThhYzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMjE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkNTU0NGQ2YTJlNzBmZmE2ODY1ZTExNmQyMjQ4ZTViMDEzMDBmNmVkZWQxZmMyMmE1NGExYWQ3OTg5ZjAwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lo-Mi0bYAL5idU9T37eIUWLX5b0nBbhdhQWuYY10kV4) [ ![Show case of some examples](https://private-user-images.githubusercontent.com/2182637/314914116-2b533f88-bf3f-402f-93f2-74a466918ac4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNTM2MDksIm5iZiI6MTcxMjM1MzMwOSwicGF0aCI6Ii8yMTgyNjM3LzMxNDkxNDExNi0yYjUzM2Y4OC1iZjNmLTQwMmYtOTNmMi03NGE0NjY5MThhYzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMjE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkNTU0NGQ2YTJlNzBmZmE2ODY1ZTExNmQyMjQ4ZTViMDEzMDBmNmVkZWQxZmMyMmE1NGExYWQ3OTg5ZjAwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lo-Mi0bYAL5idU9T37eIUWLX5b0nBbhdhQWuYY10kV4) ](https://private-user-images.githubusercontent.com/2182637/314914116-2b533f88-bf3f-402f-93f2-74a466918ac4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNTM2MDksIm5iZiI6MTcxMjM1MzMwOSwicGF0aCI6Ii8yMTgyNjM3LzMxNDkxNDExNi0yYjUzM2Y4OC1iZjNmLTQwMmYtOTNmMi03NGE0NjY5MThhYzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMjE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkNTU0NGQ2YTJlNzBmZmE2ODY1ZTExNmQyMjQ4ZTViMDEzMDBmNmVkZWQxZmMyMmE1NGExYWQ3OTg5ZjAwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lo-Mi0bYAL5idU9T37eIUWLX5b0nBbhdhQWuYY10kV4) [ ](https://private-user-images.githubusercontent.com/2182637/314914116-2b533f88-bf3f-402f-93f2-74a466918ac4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNTM2MDksIm5iZiI6MTcxMjM1MzMwOSwicGF0aCI6Ii8yMTgyNjM3LzMxNDkxNDExNi0yYjUzM2Y4OC1iZjNmLTQwMmYtOTNmMi03NGE0NjY5MThhYzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMjE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkNTU0NGQ2YTJlNzBmZmE2ODY1ZTExNmQyMjQ4ZTViMDEzMDBmNmVkZWQxZmMyMmE1NGExYWQ3OTg5ZjAwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lo-Mi0bYAL5idU9T37eIUWLX5b0nBbhdhQWuYY10kV4)

But how do we add add the styling to animate the cards when moving it around if we use the `@atlaskit/pragmatic-drag-and-drop-react-beautiful-dnd-migration`?
