### ISSUE TITLE
Adapter: Element adapter link in documentation broken.

### ISSUE THREAD

**Issue by IanBellomy** [atlassian/pragmatic-drag-and-drop#39]
Assume the link should go here : https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about

https://github.com/atlassian/pragmatic-drag-and-drop/assets/17239616/e7737acd-eff7-494f-894f-e08263337e69

**Comment by alexreardon** [comment]
Thanks! I'll fix this up. Sadly we don't yet have a broken link tracker for our site 🙃

**Comment by vr-varad** [comment]
@alexreardon I would love to work on a broken link checker or tracker on the site.
Could u please provide more info on this topic.

**Comment by alexreardon** [comment]
Doc fixes are being merged now. Thanks @IanBellomy
