### ISSUE TITLE
support drag and drop inside iframe

### ISSUE THREAD

**Issue by sakib412** [atlassian/pragmatic-drag-and-drop#48]
I tried to implement drag and drop in an iframe, but seems no event is firing. I tried with your [example](https://github.com/atlassian/pragmatic-drag-and-drop/blob/main/packages/docs/examples/pieces/iframe-board/column.tsx).  I cannot find any iframe specific settings in it. but it clone the whole react app into iframe somehow, how and why this is happened, I have no idea(i did not find the code) 😞 

Here is my [implementation](https://codesandbox.io/p/sandbox/pdnd-6kx73c?file=%2Fsrc%2FApp.tsx%3A2%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvt7i6qm00063b6l2dc1thph%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvt7i6ql00023b6lkwknzpjw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvt7i6ql00033b6llnauaf41%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvt7i6ql00053b6l36eqgi8o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.561516354180924%252C48.438483645819076%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvt7i6ql00023b6lkwknzpjw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvt7i6ql00013b6l0nf1z2dt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvt7n15t00023b6l99ho8rt7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvt7i6ql00023b6lkwknzpjw%2522%252C%2522activeTabId%2522%253A%2522clvt7n15t00023b6l99ho8rt7%2522%257D%252C%2522clvt7i6ql00053b6l36eqgi8o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvt7i6ql00043b6l36a2bh9w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvt7i6ql00053b6l36eqgi8o%2522%252C%2522activeTabId%2522%253A%2522clvt7i6ql00043b6l36a2bh9w%2522%257D%252C%2522clvt7i6ql00033b6llnauaf41%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvt7i6ql00033b6llnauaf41%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

Works fine outside of iframe, but not working inside iframe. 

In react-dnd I was doing this: 
```ts
import {useContext, useEffect} from 'react';
import {DndContext} from 'react-dnd';
import {FrameContext} from 'react-frame-component';

const DndProviderWrapper = ({children}) => {
  const {dragDropManager} = useContext(DndContext);
  const {window} = useContext(FrameContext);

  useEffect(() => {
    // @ts-ignore
    dragDropManager.getBackend().addEventListeners(window);
  });

  return children;
};

export default DndProviderWrapper;
```
But I cannot figure out how to do this in pragmatic

**Comment by alexreardon** [comment]
Within the frame you would use an element adapter - same as any other document. If you want to respond to drag operations that started outside of the iframe, then you can use the external adapter for that. 

Hopefully that clears things up. Any more questions please let me know

**Comment by jepezi** [comment]
@sakib412 Have you resolved your issue dragging within iframe? I have the same problem today and am scratching my head all day.

@alexreardon If you check codesandbox link from OP, you'll notice that you can drag but there're no events fired at all. This happens even with typical iframe and portal (without the react-frame-component wrapper).

Is it possible that the drag event does happen within iframe but nobody listens to it because the listener bound to parent document outside the iframe, hence no event firing in, say, onDragStart?

**Comment by sakib412** [comment]
> @sakib412 Have you resolved your issue dragging within iframe? I have the same problem today and am scratching my head all day.
> 
> @alexreardon If you check codesandbox link from OP, you'll notice that you can drag but there're no events fired at all. This happens even with typical iframe and portal (without the react-frame-component wrapper).
> 
> Is it possible that the drag event does happen within iframe but nobody listens to it because the listener bound to parent document outside the iframe, hence no event firing in, say, onDragStart?

No, I don't find any solution for this. So I switched back to react-dnd.

**Comment by alexreardon** [comment]
Okay, I think I have a good grip on this. I'll post an update soon

**Comment by alexreardon** [comment]
See https://github.com/atlassian/pragmatic-drag-and-drop/issues/24#issuecomment-2290171561
