### ISSUE TITLE
Drag and drop does not work in Chrome dev tools device mode

### ISSUE THREAD

**Issue by MichaelJOHare** [atlassian/pragmatic-drag-and-drop#52]
If you go to the tutorial page and open dev tools and select iphone 14 pro max from the device list and try to drag the king piece it doesn't work. Is this just a limitation of the device mode in chrome dev tools?  It works if done from my actual phone, albiet not great because of #13, but not in the dev tools device mode.

**Comment by alexreardon** [comment]
This looks to be a limitation with dev tools. If you would like to have this issue actioned, you could raise a an issue [on the Chromium project](https://issues.chromium.org/issues/wizard)

**Comment by nmhungdev** [comment]
Hey @alexreardon , @MichaelJOHare !
It does not limit the device mode in Chrome DevTools. It works properly on DnD Kit [Story Book](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-grid--basic-setup) or [Sandbox](https://22x1ix.csb.app/)
