### ISSUE TITLE
dynamic-table - Is there any plan to support to react 18?

### ISSUE THREAD

**Issue by hyungyun** [atlassian/pragmatic-drag-and-drop#53]
Hi~  I want to use dynamic-table but you know it isn't supporting react 18.
So, if you have a plan to upgrade to react 18? or I missed some information that you already support react 18 then feel free tell me.

Thanks.

**Comment by alexreardon** [comment]
Hi there, dynamic table is an Atlassian Design System output and not related to this project. You can provide feedback on dynamic table here:

https://atlassian.design/components/dynamic-table/examples
