### ISSUE TITLE
Changelog / Release notes?

### ISSUE THREAD

**Issue by axeleroy** [atlassian/pragmatic-drag-and-drop#58]
Hello,

Is there a changelog for Pragmatic Drag and Drop? I have not been able to find one and it would be very useful to know which bugs, breaking changes and new features may have been respectively fixed, introduced and added in a new version.

Regards,
Axel

**Comment by re-thc** [comment]
It's on the website? Are you referring to [https://atlassian.design/components/pragmatic-drag-and-drop/core-package/changelog/changelog](https://atlassian.design/components/pragmatic-drag-and-drop/core-package/changelog/changelog)?

**Comment by axeleroy** [comment]
Oh sorry, I could not find it. Thanks!
