### ISSUE TITLE
Bug: Safari Autoscroll Offset

### ISSUE THREAD

**Issue by nikischin** [atlassian/pragmatic-drag-and-drop#60]
I noticed some behavior trying your[ autoscroll example](https://atlassian.design/components/pragmatic-drag-and-drop/optional-packages/auto-scroll/about). When there's some scrolling done, the drag over is getting slightly offset in Safari 17.5 in macOS.

![Scroll Offset Safari](https://github.com/atlassian/pragmatic-drag-and-drop/assets/49103409/41971870-89d7-4086-a281-b9200d551dca)

I noticed some similar behavior in other DnD libraries already, so I assume it might be a browser bug maybe. Interesting enough it is fixed again once you reach scroll end and is only an issue on scroll down and not on scroll up. The further you scroll down, the bigger the offset gets.

**Comment by alexreardon** [comment]
Hi there!

I think you might be bumping into this browser bug: https://bugs.chromium.org/p/chromium/issues/detail?id=410328

**Comment by alexreardon** [comment]
I will continue to chase that browser bug

**Comment by SMYusupov** [comment]
Hey @alexreardon! I am still facing the issue. I don't think that it is related to the link bug that you've attached. I've watched your honey pot fix, and I think it is not the same problem that is listed here. I see this bug only in Safari and was not able to reproduce it on Chrome. As I understand the problem, Safari makes an incorrect calculation of the elements' positions, resulting in a mismatch between how it looks and how it works. It starts to work fine after a little bit of scrolling, and it is not reproducible when the element drops after fully scrolling down. Could we reopen the issue?


Here is example, I've added hover state color, so you can see item's color change on hover, and it shows hover state, even when pointer is not over the element. When I opened devtools - it shows different layout (image)

https://github.com/user-attachments/assets/0ac7b7f0-fd05-47c8-9374-27953c9f4cf0

<img width="155" height="385" alt="Image" src="https://github.com/user-attachments/assets/73f0e166-f7dd-45ee-a072-f42ed18863bd" />
