### ISSUE TITLE
Links in Documentation are broken

### ISSUE THREAD

**Issue by nikischin** [atlassian/pragmatic-drag-and-drop#61]
Pretty much all links in your tutorial page at https://atlassian.design/components/pragmatic-drag-and-drop/tutorial are broken. Instead of linking to the related page, the path is added to the url relatively and the url gets longer on every click. 

Seems like someone mixed up relative paths. You might also check the examples page which includes the same behavior https://atlassian.design/components/pragmatic-drag-and-drop/examples and other pages like https://atlassian.design/components/pragmatic-drag-and-drop/web-platform-design-constraints

I did not check each and every page and link but also the other pages include broken links. Not each and every link seems to be broken though, but many are.

Thank you in advance!

**Comment by Jenyadio** [comment]
Agree
Very inconvenient to read the documentation, almost all links are broken, can you please fix it

**Comment by MatchuPitchu** [comment]
The problem still exists and confused me when reading the documentation.

**Comment by michaelabrahamian** [comment]
Thanks for the heads up! We're fixing these now 👀

**Comment by mrclrchtr** [comment]
Thank you very much!

Should we report broken links?

**Comment by michaelabrahamian** [comment]
@mrclrchtr Absolutely!

**Comment by mrclrchtr** [comment]
I found these:

https://atlassian.design/components/pragmatic-drag-and-drop/core-package/drop-targets#drop-target-arguments

```
[onGenerateDragPreview](https://atlassian.design/components/pragmatic-drag-and-drop/events)
[onDragStart](https://atlassian.design/components/pragmatic-drag-and-drop/events)
[onDrag](https://atlassian.design/components/pragmatic-drag-and-drop/events)
[onDropTargetChange](https://atlassian.design/components/pragmatic-drag-and-drop/events)
[onDrop](https://atlassian.design/components/pragmatic-drag-and-drop/events)
```

**Comment by michaelabrahamian** [comment]
Thanks @mrclrchtr! 

We've gone through all the pragmatic docs pages and all broken links should now be fixed. Please let us know if you find any more though!
