### ISSUE TITLE
Example of html element DnD across browser windows?

### ISSUE THREAD

**Issue by twarenius** [atlassian/pragmatic-drag-and-drop#73]
Hi!

I've been trying to find out if it's possible to drag and drop html elements between browser windows. I have seen it mentioned that you should be able to drag and drop stuff between windows/browser but haven't really seen it documented or any examples of it other than the external adapters and the documentation for dropTargetForExternal and monitorForExternal but that doesn't really mention the dragging of html/dom elements. It seems to be more of handling textual content in the form of text/html/urls and files.

Is it technically possible to do this type of drag and drop? Can it be done with pragmatic-drag-and-drop in the state it is in today?

The use case is to have the application split up on several screens/monitors with a few modules on each screen and have the possibility to drag items from a list in one window to another list in another window. Like having two Jira boards open in separate browser windows and dragging items between them.

I have got it working with dragging in text and urls from other browser windows using the dropTargetForExternal but as soon as I try to drag html elements out of a window it doesn't seem _droppable_ anywhere.

/ Thomas

**Comment by alexreardon** [comment]
> Is it technically possible to do this type of drag and drop? Can it be done with pragmatic-drag-and-drop in the state it is in today?

Yep!

> I try to drag html elements out of a window it doesn't seem droppable anywhere.

The [`draggable.getInitialDataForExternal()`](https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about#data-for-external-consumers-getinitialdataforexternal) allows you attach data for external consumers (eg other windows) to an element

Any further questions just let me know
