### ISSUE TITLE
[Request] Atlassian Examples

### ISSUE THREAD

**Issue by alyoung1621** [atlassian/pragmatic-drag-and-drop#84]
### Discussed in https://github.com/atlassian/pragmatic-drag-and-drop/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **alyoung1621** July  3, 2024</sup>
I originally posted this in the discussions, but thought it might be more appropriate as a request/issue.

On the Atlassian examples page, the code is provided via CodeSandbox. Per [CodeSandbox](https://sandpack.codesandbox.io/docs/resources/faq#what-license-do-sandpack-and-nodebox-use), Nodebox cannot be used for commercial use. Is it possible to make the source code available for each example in separate repos? The documentation package [README](https://github.com/atlassian/pragmatic-drag-and-drop/tree/main/packages/documentation), containing the examples folder, indicates it is not intended for direct use by consumers.</div>

**Comment by alexreardon** [comment]
Let's continue in the discussion :)
