### ISSUE TITLE
Is it possible to trigger a drag via events other than left mouse button click?

### ISSUE THREAD

**Issue by yarv-dev** [atlassian/pragmatic-drag-and-drop#86]
Is it possible to trigger a drag via events other than left mouse button click? 
For example:
- trigger onDrag() via button 1 (middle mouse button) or button 2(right click).

I can see some form of related data in canDrag()DraggableGetFeedbackArgs, but have not seen any clear example of triggering a drag via anything other than primary mouse button, possibly i am missing something?

**Comment by alexreardon** [comment]
Pragmatic drag and drop exclusively leverages the browsers built in drag and drop functionality. We are at the mercy of how browsers decide that drag and drop should be done by users (including what inputs can trigger a drag operation). 

Good news though: these behaviours are shared across the web and users will be trained to use these behaviours.
