### ISSUE TITLE
Dnd rectangle spanning multiple squares

### ISSUE THREAD

**Issue by MarcoLeti** [atlassian/pragmatic-drag-and-drop#87]
In the Chessboard tutorial we have the case where a chess piece is contained inside one square. This is the easiest case. What's the best way to drag and drop, for example, a rectangle which spans over two or more squares (like for example in an appointment scheduler)? Thanks

**Comment by alexreardon** [comment]
With pragmatic drag and drop - you can create any setup you want.

- a draggable can be any element
- a drop target can be any element
- draggables can be infinitely nested
- drop targets can be infinitely nested
- a whole element can be draggable from just a part of it (drag handle) and you can make the preview look like whatever you want too
