### ISSUE TITLE
Press and hold to drag is problematic in Grid example (iOS)

### ISSUE THREAD

**Issue by aarjithn** [atlassian/pragmatic-drag-and-drop#9]
Currently for drag to start, you need to press and hold (this was not very obvious so I initially thought drag doesn't work in mobile).

The problem is when what you are trying to drag is an image - in that case iOS does this.

![image](https://github.com/atlassian/pragmatic-drag-and-drop/assets/10304259/c4a44272-f10e-43cf-a13d-387e7c9c8491)

Is it possible to just drag instead of having to press and hold? Dndkit / formkit dnd etc works that way

**Comment by alexreardon** [comment]
We are not in control of when the drag starts - we are listening exclusively to the web platforms built in drag and drop events. I'll take a look and see if this example can be improved for iOS

**Comment by alexreardon** [comment]
Thankfully it's pretty easy to fix:

- add `'-webkit-touch-callout': 'none'` to the item (to disable the "save image" popup)
- change the drop effect on the cards from 'link' to 'copy' (it looks like "link" doesn't work that well on iOS)

The platform can be fun sometimes!

**Comment by alexreardon** [comment]
I'll merge these changes into our examples, and you should see the updates in this repo and on our docs in ~12 hours
