### ISSUE TITLE
Can I carry a node parameter during ondrag and call this parameter during ondrop? 

### ISSUE THREAD

**Issue by Sinongamess** [atlassian/pragmatic-drag-and-drop#95]
For example, carry an HTMLElement during ondrag

**Comment by alexreardon** [comment]
I am not sure what you mean by "carry an HTMLElement". Do you mean drag and drop? In which case - you will want the element adapter: https://atlassian.design/components/pragmatic-drag-and-drop/core-package/adapters/element/about

You can attach any data you like to a draggable using `getInitialData()`. You can also attach any data you want to a drop target using `getData()`.
