### ISSUE TITLE
onDragStop event exists?

### ISSUE THREAD

**Issue by idan-h** [atlassian/pragmatic-drag-and-drop#98]
I can't seem to find an event when a drag is stopped? meaning, if we didn't drop on a target and canceled the operation.

I want to find an event that will always tell me if a drag is stopped, no matter what.

**Comment by alexreardon** [comment]
You can use `onDrop` for this. The `location.current.dropTargets` array will be empty when dropping on no drop targets.

If you want to get all `onDrop` events regardless of whether a drop target is dropped on, you can use a `monitor` which is notified about all events
